# Generated by Django 3.2.4 on 2021-06-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailloginattempt',
            name='ip_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
